from autogen_agentchat.agents import AssistantAgent
from autogen_agentchat.messages import TextMessage
from autogen_core import CancellationToken


class ValidatorAgent:
    """
    Validator agent responsible for ensuring the correctness, reliability,
    and robustness of outputs generated by other agents.

    Responsibilities:
    - Validates results for logical correctness and consistency
    - Tests and checks workflows or pipelines
    - Ensures outputs are reliable and meet expected standards
    - Provides feedback or flags issues for improvement

    This agent focuses purely on verification and validation of results.
    """

    def __init__(self, model_client):
        """
        Initializes the Validator agent with a language model client.
        """

        self.agent = AssistantAgent(
            name="validator",
            system_message="""
            You are the Validator agent.
            Validate correctness, test pipeline, ensure reliability.
            """,
            model_client=model_client
        )

    async def run(self, task):
        """
        Validates a given task or output and returns evaluation results.
        Sends the task or output to the underlying AssistantAgent and retrieves
        feedback on correctness, reliability, and potential issues.
        """

        cancellation = CancellationToken()

        response = await self.agent.on_messages(
            [TextMessage(content=task, source="user")],
            cancellation
        )

        return response.chat_message.content
